title: Kalndzirnavas
email: kalndzirnavas@gmail.com
description: Skatu vieta Kalndzirnavas
  
baseurl: https://www.kalndzirnavas.lv
url: "www.kalndzirnavas.lv"

plugins:
  - jekyll-multiple-languages-plugin

exclude:
  - README.md
languages: ["lv", "en", "et"]
exclude_from_localizations: ["assets", "css", "js", "README.md"]