title: Kalndzirnavas
email: kalndzirnavas@gmail.com
description: Skatu vieta Kalndzirnavas
  
baseurl: /kalndzirnavas
url: ""

plugins:
  - jekyll-multiple-languages-plugin

exclude:
  - README.md
languages: ["lv", "en", "et"]
exclude_from_localizations: ["assets", "css", "README.md"]