title: Kalndzirnavas
email: kalndzirnavas@gmail.com
description: Skatu vieta Kalndzirnavas
  
baseurl: ""
url: "https://kalndzirnavas.lv"

plugins:
  - jekyll-multiple-languages-plugin

exclude:
  - README.md
  - publish.sh
languages: ["lv", "en", "et"]
exclude_from_localizations: ["assets", "css", "js", "README.md"]
keep_files: ['CNAME']